version: '3.8'
services:
  db:
    container_name: mssql_container2022
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Topcon1932
      # MSSQL_PID: TopconD
    volumes:
      - mssql2022:/var/opt/mssql
    ports:
      - "1433:1433"
volumes:
  mssql2022:
